title: A Cosmology Group
description: Observations, inferences and the fading confidence in Î›CDM cosmology
theme: just-the-docs

url: https://a-cosmology-group.github.io/acg/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/a-cosmology-group/acg
